apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: lt-operator.kyma-project.io
  name: lt-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lt-operator-manager-role
subjects:
- kind: ServiceAccount
  name: lt-operator-controller-manager
  namespace: lt-operator-system
