apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: lt-operator.kyma-project.io
  name: lt-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
