apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: lt-operator.kyma-project.io
    control-plane: controller-manager
  name: lt-operator-controller-manager-metrics-service
  namespace: lt-operator-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: lt-operator.kyma-project.io
    control-plane: controller-manager
