# permissions for end users to edit longoperations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: longoperation-editor-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - longoperations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - longoperations/status
  verbs:
  - get
