# permissions for end users to view longoperations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: longoperation-viewer-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - longoperations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - longoperations/status
  verbs:
  - get
