---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - longoperations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - longoperations/finalizers
  verbs:
  - update
- apiGroups:
  - operator.kyma-project.io
  resources:
  - longoperations/status
  verbs:
  - get
  - patch
  - update
